### PR TITLE
Fix Ansible playbook reference

### PR DESCRIPTION
**Pull request by i-ky**
Looks like Vagrantfile was overlooked in ab910519aad3e1ae71636a4e21f537112448525a

Old playbook is also referenced [here](https://github.com/klee/klee-web/blame/master/doc/VAGRANT.md#L27), but I'm not knowledgeable enough to fix it too.

### CODE REVIEW

**Comment by ccadar** [comment]
Thanks, @i-ky , good catch.  However, before merging this, I'd like to have Circle CI fixed.  

@andronat , @Denis-Gavrielov, maybe you have time to take a look?

**Comment by i-ky** [comment]
I guess CircleCI is affected by #156...

**Comment by andronat** [comment]
Hello @i-ky and thanks for the PR!

This should work after #157 is merged.

**Review by andronat — APPROVED** [review]

**Comment by ccadar** [comment]
@i-ky please rebase.

**Comment by i-ky** [comment]
> @i-ky please rebase.

Done.

**Pull request merged**
