### PR TITLE
Fixed CircleCI ubuntu image version and merged dependabot branches

### PR DESCRIPTION
**Pull request by kt218**

### CODE REVIEW

**Comment by andronat** [comment]
Hey @kt218 may I please ask you to squash all of the commits together with an explanation on the updates?

**Comment by ccadar** [comment]
@kt218 Was this only issue with CircleCI the ubuntu image?  If so, I would do this separately and then merge the dependabot PRs separately.

**Comment by ccadar** [comment]
@kt218 let's try to merge this, can you push it again?  Not sure why the checks haven't run.

**Comment by kt218** [comment]
@ccadar I've tried doing a different merge request but it appears that it doesn't perform the check either.

**Comment by ccadar** [comment]
@ccadar I assume something change on Circle CI's side.  
Can you look at https://circleci.com/docs/2.0/troubleshooting-common-issues/ ?

**Comment by kt218** [comment]
@ccadar I think I triggered the check now, by manually doing it through CircleCI ui and it appears there's an issue with the last line in config.yml

**Comment by ccadar** [comment]
Do you know how to fix that line?

**Comment by kt218** [comment]
@ccadar I'm unsure about the issues, it looks like it's related to apt-get and some repository issue. I'm trying some changes to see if it will fix the issue.

**Comment by ccadar** [comment]
I think there are two issues here: the CI failing (which might be fixed by your changes) and the CI not being triggered at all.  Right?

**Comment by kt218** [comment]
Yes, there's 2 issues. I'm still unable to fix the 1st issue. I'm looking around to see why apt-get is interfering with ansible. As for CI not getting automatically triggered, it might be some setup on CircleCI side that not entirely fixed from the last time the api key was changed.

**Comment by ccadar** [comment]
@kt218 I think I solved the issue of the CI not being triggered from the CircleCI UI.
But I'm still confused as to why there are two checks, "workflow" and "ci/circleci:build"

**Comment by kt218** [comment]
I think they are the same, since ci/circle: build is under workflow when looking through the [Checks](https://github.com/klee/klee-web/pull/185/checks) tab on github.

**Comment by kt218** [comment]
@ccadar It's a bit ugly but I've resolved the first issue with CI failing, by making sure that the CI always grabs the latest public key for heroku.

**Comment by ccadar** [comment]
Great!  Just squash the commits to config.yml and we can merge it

**Comment by kt218** [comment]
@ccadar Commits squashed to config.yml

**Review by ccadar — APPROVED** [review]
Thanks, nice to have the CI working again; looking forward to more improvements!

**Comment by ccadar** [comment]
@kt218 Don't close the dependabot PRs for now; I'd like to understand why the CI does not trigger for forked repositories.

**Pull request merged**
