### PR TITLE
Replace docker role and fix python libraries

### LINKED ISSUE #125: angstwad.docker_ubuntu does not install docker-py
Vagrant up fails on `TASK redis : Docker pull Redis 3.2`

The problem seems to be a missing installation of docker-py. Maybe investigate to find another plug-in to install docker.

### PR DESCRIPTION
**Pull request by andronat**
Fixes #125

### CODE REVIEW

**Comment by Denis-Gavrielov** [comment]
Performing rebase and merge.

**Comment by ccadar** [comment]
What happened to the Circle CI check?

**Comment by andronat** [comment]
Fixes are coming soon!

**Comment by ccadar** [comment]
Great to hear!  And I think it's important with new changes coming up.

**Pull request merged**
