### PR TITLE
Added 2019 team and maintainer info to AUTHORS file.

### PR DESCRIPTION
**Pull request by ccadar**

### CODE REVIEW

**Comment by ccadar** [comment]
@Denis-Gavrielov if you'd like to help maintain the project going forward, I'd be delighted to add you in that role too.

**Review by andronat — DISMISSED** [review]

**Comment by andronat** [comment]
@ccadar I think you need to disable the `ci/cirlceci: build` as we don't have a `workflow` setup in klee's circleci. You can do this as shown [here](https://circleci.com/docs/2.0/workflows-waiting-status/). The `ci/cirlceci` should run everything.

**Comment by Denis-Gavrielov** [comment]
@ccadar sure, I would be happy to help out and especially ensure that the changes around my dissertation are approved going forward.

**Comment by ccadar** [comment]
@andronat thanks -- somehow I understood from @Denis-Gavrielov that the `ci/circleci: build` needs to be checked.  I now switched to `ci/circleci`

**Comment by ccadar** [comment]
@Denis-Gavrielov great!  I'll then add you to the maintainers list, and resubmit my patch.

**Comment by ccadar** [comment]
@Denis-Gavrielov and/or @andronat if you're happy with this, can you approve it and merge it?

**Review by andronat — APPROVED** [review]

**Pull request merged**
