### PR TITLE
Frontend: UI, sidebar and editor fixes

### PR DESCRIPTION
**Pull request by jamesreaver**
- Fix a bug which prevented the "Add New Projects" option from being shown when logged in.
- Fix a bug which caused the editor scrollbar to be displayed outside the editor area.
- Fix a bug which was hiding the projects in the drop-down selection menu.
- Display the username fully in the top bar, instead of truncating it.

### CODE REVIEW

**Comment by jamesreaver** [comment]
Rebased. Checked and ready to merge.

**Comment by andronat** [comment]
Can you include a small test for the first problem (first bullet)?

**Comment by andronat** [comment]
@giacomoguerci did you push the test?

**Comment by jamesreaver** [comment]
@andronat I'm going to write the test tomorrow. I'll let you know so you can approve this PR and we can merge it, since it includes some important fixes to the frontend.

**Comment by ccadar** [comment]
Hi @giacomoguerci , I managed to test this on my machine after a `vagrant destroy`, but I see the following bug: after using the scroll bar, if I press "Options", the menu is shown _behind_ the scroll bar.  Can you observe this too?

**Comment by jamesreaver** [comment]
I can @ccadar, thank you for reporting. I fixed it.

**Comment by ccadar** [comment]
This was fast!  But you didn't push the commit.

**Comment by jamesreaver** [comment]
I've had some problems with grunt so I wasn't able to complete my commit with that UI fix @ccadar. I will try tomorrow. @andronat I've added the test to check that logged in users can see the Add New Project option.

**Pull request merged**
