### PR TITLE
Remove deprecated features and switch to klee/klee

### PR DESCRIPTION
**Pull request by helicopter88**
This is just the removal of some deprecated features, like sudo and tags.
For sudo, become is now used(and become_user for sudo_user) and for tags, the new syntax is used.
Also, libffi-devel has been added as an apt package, but I am not too sure about its location

### CODE REVIEW

**Comment by andronat** [comment]
+1

**Comment by andronat** [comment]
circleci fails due to kleeweb container rebuilding. We should address this.

**Comment by helicopter88** [comment]
There is a problem with the fetching of a GPG key, I think that makes docker fail.
They key is however located on some LLVM website, so I don't think I can do much about it if that's the case

**Comment by andronat** [comment]
circleci fails when it tries to execute `docker build` on [this docker file](https://github.com/klee/klee-web/blob/master/src/klee_web/worker/docker/Dockerfile).

We don't need this Dockerfile anymore as we pull klee's official docker image.

In your commit here: 7341300cec03ea5c8bd521171083031ab15edab8 you [line 19](https://github.com/klee/klee-web/pull/65/commits/7341300cec03ea5c8bd521171083031ab15edab8#diff-29944324a3cbf9f4bd0162dfe3975d88R19) you just changed the tag name of the image but you still building it. You have to change the logic to make it work properly.

**Comment by helicopter88** [comment]
It seems to start docker fine, however I haven't set the vault password in ENV so it can't run properly.

**Comment by ccadar** [comment]
+1 too.  I also tested it on my machine, and this fixes the vagrant issues I had.  Since removing those passwords and making CircleCI work might take a while and we need these changes, I'll merge this now.

**Pull request merged**
