### PR TITLE
Fix timeout of Docker containers

### PR DESCRIPTION
**Pull request by andronat**
Depends on #147

### CODE REVIEW

**Comment by ccadar** [comment]
@andronat this one needs to be rebased now.

**Comment by andronat** [comment]
@ccadar done!

**Comment by ccadar** [comment]
Thanks, @andronat .  I'm a bit confused about the timeout code, as I see three different values there.  Which one is what?  Should we have that in a single place, so that we can easily change it when needed?

**Comment by andronat** [comment]
Hmm, where do you see the 3 different values? It's only 1 [here](https://github.com/klee/klee-web/pull/148/commits/52b39818c4d95db352aebde7dd520031152210ab#diff-6d461b2e3e065fb3a23197d28446d9e7R89) which is the default of 10 min for every execution. 😕

**Comment by andronat** [comment]
Do you mean there [here](https://github.com/klee/klee-web/pull/148/commits/52b39818c4d95db352aebde7dd520031152210ab#diff-1ced9eebc7ae3bd1f94ca6bbafc6f2fdR75)? This is only a test that overwrites the default value to 1 second to test a dummy docker container that executes a sleep of 10 seconds.

**Comment by ccadar** [comment]
Got it, not sure why I was confused about that.  
So is the timeout now is 600s, specified here? 
https://github.com/klee/klee-web/blob/80e777cc48699f696015c239c819f2fb14b30625/src/klee_web/worker/runner.py#L89

Or is it just the timeout for tests?

**Comment by andronat** [comment]
Yes the timeout is 600s. I'm actually just pushed another commit to make this configurable from `WorkerConfig` which is the main configuration file for the worker.

**Comment by ccadar** [comment]
Thanks, again, @andronat !

**Review by ccadar — APPROVED** [review]

**Pull request merged**
