### PR TITLE
Add more workers and encrypt login details

### PR DESCRIPTION
**Pull request by helicopter88**
Keep all the login details hidden under the vault key

### CODE REVIEW

**Comment by andronat** [comment]
Question: would be possible to put all there vars in one file?

**Comment by helicopter88** [comment]
There's a file called all, but it contains other definitions that shouldn't be encrypted

**Comment by andronat** [comment]
Look [here](http://leucos.github.io/ansible-files-layout/). `all` can be a folder and you can create `all/all` and `all/all_sercret`.

**Comment by helicopter88** [comment]
Done, now everything is in all_secret

**Pull request merged**
