### PR TITLE
Froze a dependency related to django

### PR DESCRIPTION
**Pull request by andronat**

### CODE REVIEW

**Comment by andronat** [comment]
:tada: @ccadar. Merge this at your discretion.

**Comment by ccadar** [comment]
This LGTM, thanks, @andronat . Can I just ask why you added the `--ignore=E722` option?

**Comment by ccadar** [comment]
@andronat I assume we still want to merge this?  I thought a comment about `--ignore=E722` would be useful, otherwise, we could merge it, unless newer PRs supersede this.

**Comment by andronat** [comment]
i'll check this asap and how it interacts with the other PRs.

**Review by Denis-Gavrielov — APPROVED** [review]
LGTM

**Pull request merged**
