### PR TITLE
Changed tag latest to using a specfic digest.

### PR DESCRIPTION
**Pull request by kt218**
Use specific digest when retrieving KLEE image.
Result of retrieving image is used to tag as latest on local.

### CODE REVIEW

**Comment by kt218** [comment]
I'm not sure how to achieve this https://github.com/klee/klee-web/pull/197#issuecomment-1162388317.
Instead I'm now using the image digest directly.

**Comment by ccadar** [comment]
@MartinNowack, I assume this is what you had in mind?

**Comment by MartinNowack** [comment]
Yes - but I would recommend to simplify it.

Allow `klee_version` to be either:
* `:tag`, or
* `@sha256:...`

In this case you can change between both notations arbitrarily in future versions.
(Maybe  add a comment of the expected format to the `klee_version` variable)

**Comment by kt218** [comment]
I have tried having the @ within the `all` file to be `@sha256:..`, but it hasnt worked out for me and I'm unsure how to escape it properly for Ansible to view it correctly.

**Comment by MartinNowack** [comment]
@kt218 Looks great!

**Review by andronat — APPROVED** [review]

**Pull request merged**
