### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by Denis-Gavrielov**
Dockerize all the components of the application. 
The components are:

- Nginx container
- Django and Frontend (Angular framework) container
- PostgreSQL container
- Worker container
- Redis container

The Ansible rules now separate the build and deployment of the containers. Tags are added which can be used to re-build and deploy only specific containers to speed up provisioning once the VM is running. 

The disk size on the Vagrant VM for the development environment is increased. This is dependent on a vagrant plugin. The README is updated to instruct installing this plugin before running `vagrant up`.

Additionally, I have updated the provisioning rules for the production and development environment to reflect an architecture which has one Master VM, one to many Worker VMs, and one Testing VM.

### CODE REVIEW

**Comment by andronat** [comment]
Let's rebase this too! 🎉

**Comment by Denis-Gavrielov** [comment]
@andronat done! Note there is still some minor WiP which includes:

- checking if the postgresql container is persistent. Do you have some advice to ensure that?
- Updating Python base images to 3.7

**Comment by Denis-Gavrielov** [comment]
Please note, there seems to be an issue with celery that the worker stops listening to request if a celery heartbeat is missed. 
These are some threats that I found where people seemed to have similar issues:
https://github.com/celery/celery/pull/4997
https://github.com/celery/celery/issues/4185
https://github.com/analyseether/ether_sql/issues/42
https://github.com/celery/celery/issues/2296

Right now, there is a cronjob that checks every hour if the worker's log shows a missed heartbeat and restarts the container in that case. This works fine for now, but there might be more elegant solutions for the future.

**Comment by ccadar** [comment]
@Denis-Gavrielov I would add this last comment as a separate issue.

**Comment by Denis-Gavrielov** [comment]
@ccadar done

**Comment by ccadar** [comment]
Thanks!

**Comment by ccadar** [comment]
@Denis-Gavrielov can you rebase this branch so that the tests run again?
@andronat is this close to being merged?

**Review by andronat — APPROVED** [review]

**Comment by andronat** [comment]
Merged in #137.

**Pull request closed without merging**
