### PR TITLE
Rework e2e tests

### PR DESCRIPTION
**Pull request by andronat**

### CODE REVIEW

**Comment by ccadar** [comment]
Thanks, @andronat , this looks good overall, ping me when it's finalized.

**Comment by andronat** [comment]
This is ready now. Feel free to merge.

**Comment by ccadar** [comment]
@andronat can you explain why you had to disable those tests?  How soon will you be able to re-enable them?

**Comment by andronat** [comment]
The python tests are tightly coupled with the kleeweb-worker code base. I wanted to extract the e2e tests in a different docker container in order to contain the complexity. I'm reenabling them in the PR which is coming after #146.

**Comment by ccadar** [comment]
@andronat sounds good, just don't forget about them!  Thank again for the nice changes!

**Review by ccadar — APPROVED** [review]

**Comment by andronat** [comment]
I won’t. I written some new ones too. I want them in 😂

**Pull request merged**
