### PR TITLE
Update python & javascript dependencies

### PR DESCRIPTION
**Pull request by helicopter88**
This PR updates django to 1.8 and NodeJS to 6.x.
It also updates most of the used libraries to their latest or to the latest that we can run without breaking anything.

### CODE REVIEW

**Comment by helicopter88** [comment]
This solves #76

**Comment by andronat** [comment]
1. Due to some other merges more URLs were added. Double check them as they might also need updating.
2. What is this migration file doing? How is related to version updating?

**Comment by helicopter88** [comment]
Django 1.8 added more fields for user registration and login, and won't work without having them in the database, so I had to add this migration

Will have a look at the URLs

**Comment by helicopter88** [comment]
This PR is ready to be reviewed

**Pull request merged**
